apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: marketing-microservice-secret
  namespace: statex-apps
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: marketing-microservice-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/prod/marketing-microservice
        property: DB_PASSWORD
