apiVersion: v1
kind: Service
metadata:
  name: marketing-microservice
  namespace: statex-apps
  labels:
    app: marketing-microservice
    managed-by: k8s-migration
spec:
  type: ClusterIP
  selector:
    app: marketing-microservice
  ports:
    - protocol: TCP
      port: 4600
      targetPort: 4600
      name: http
